/** Declaration file generated by dts-gen */

declare module 'promise-queue' {
    export = Queue
}

declare class Queue {
    constructor(maxPendingPromises: number, maxQueuedPromises: number);

    add<T>(promiseGenerator: () => Promise<T>): Promise<T>;

    getPendingLength(): number;

    getQueueLength(): number;

    static configure(GlobalPromise: any): void;

}
