/** Declaration file generated by dts-gen */

declare module "node-object-hash" {
  export = node_object_hash;
}

declare function node_object_hash(options?: {
  coerce?: boolean // true Performs type coercion
  sort?: boolean // true Performs array, object, etc. sorting
  alg?: string // "sha256" Default crypto algorithm to use (can be overridden)
  enc?: string // "hex  Hash string encoding (can be overridden)
}): {
  hash: (obj: any) => string //Returns object hash string (see hash)
  sort: (obj: any) => string //Returns sorted object string (see sort)
};
